### ISSUE TITLE
Mosaic nonce in wrong format

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#242] opened 2020-01-17 12:22 UTC
Mosaic nonce returns in a signed integer format on testnet

http://api-harvest-20.ap-northeast-1.nemtech.network:3000/transaction/2972B07F3BAE981E4EA94BCDC03DD711C5FEE06466364511729AB52CF988098E

**Comment by Vektrat** [comment] 2020-01-17 12:25
duplicate of #144

**Closed by Vektrat** 2020-01-17 12:25 UTC
Labels: bug, duplicate
