### ISSUE TITLE
/block/:height/transactions ordering param is ignored

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#283] opened 2020-03-11 15:16 UTC
This block's transaction endpoint should order the transactions

https://github.com/nemtech/catapult-rest/blob/master/rest/src/routes/blockRoutes.js#L60

like in the account endpoints

https://github.com/nemtech/catapult-rest/blob/master/rest/src/routes/accountRoutes.js#L57

I know this going to be refactored, but we should revisit every paginated endpoint for missing params.

**Comment by Vektrat** [comment] 2020-03-11 15:21
this has never been a requirement, ordering was never a feature in the REST server and was specifically added due to demand, i'm closing this because it's not a bug and this is already being under revision with the pagination changes

**Comment by fboucquez** [comment] 2020-03-11 15:44
This is a bug because the open API specification says it's a valid parameter. 

https://github.com/nemtech/symbol-openapi/blob/master/spec/core/block/routes/getBlockTransactions.yml#L10

If we have 10 endpoints that return paginated transactions (or other entities) we should not cherry-pick which one can be sorted or not. The only reason not to do if there is an important implementation constraint, in that case we then report an issue in rest and remove the param in the open API spec.

What's the outcome then? @dgarcia360

**Comment by dgarcia360** [comment] 2020-03-19 17:42
It should have been requested to match other transactions endpoints spec, but now that this will be solved by #172 I would opt to delete the ``ordering`` parameter fo this specific endpoint.

**Comment by Vektrat** [comment] 2020-03-20 12:10
removing it in openapi in favour of incoming updates to REST

**Closed by Vektrat** 2020-03-20 12:10 UTC
