### ISSUE TITLE
/Transactions not returning transactions created using an Alias as recipient

### ISSUE THREAD

**Issue by decentraliser** [nemtech/catapult-rest#165] opened 2019-10-17 10:40 UTC
`/transactions/address` and `/transactions/publicKey` are not returning the transactions received when announced using an alias, so do the WebSockets

I don't think it was the case with E3.

So if a transaction is sent to me using my alias, I can't get it. Is it a wanted behaviour? is there a way around?

The transaction, sent to SD4GWLPNPHVJMCV3ZL2BXGNVRT6XMGYMP6KWI5JB's alias: http://47.107.245.217:3000/transaction/5938B24278EE0E77F820BE147A51E54F1921A8BEC76DAAE0DBC6445A4810A8A2

Transaction is not included here
http://47.107.245.217:3000/account/SD4GWLPNPHVJMCV3ZL2BXGNVRT6XMGYMP6KWI5JB/transactions?pageSize=100&ordering=-id

The samepayload is received when using the account's publicKey
http://47.107.245.217:3000/account/A3C001E2E98A881D2DE79EDF39B0C242E637FC07AB587AD38C5D6D27675642BC/namespaces?pageSize=100

**Comment by Vektrat** [comment] 2019-10-22 13:30
i believe the alias does not matter here, this will probably get fixed by #170

**Comment by decentraliser** [comment] 2020-01-15 06:02
hi! What is the status of this issue? 
is there any workaround?

**Comment by Vektrat** [comment] 2020-01-15 07:23
regarding the endpoint, and _not_ the websocket, this issue was supposedly fixed by #170 , do you still have this issue? can you provide specific details? also keep @martinayora in the loop, he worked in this

**Comment by decentraliser** [comment] 2020-01-15 07:36
for me its closed neither on endpoint nor websocket

Here is an example, on testnet:
This account is aliased as `satoshi.chicken`.
It has a balance of 1 `xim`, sent to it's alias. But the transaction is not showing
http://explorer.nemtech.network/account/TCMUC5CVUG7WJD25CAWJNFDYZIIVBR335D2WAHPK


Here is the transaction:
http://explorer.nemtech.network/transaction/FD63F2397F76ADBD5774A0082A5A422B890CE7620554312582F5CBE94D5CC631

**Comment by martinayora** [comment] 2020-01-15 08:31
I will check it.

**Comment by martinayora** [comment] 2020-01-20 13:21
This is happening due to transactions being filtered by account address.

When sending mosaics to an account using the alias, the alias id is used instead of the address.

As REST is not resolving alias it won't find these transactions by address only. So this is not a bug but maybe not the expected behavior.

Maybe @dgarcia360  wants to add something.

**Comment by Vektrat** [comment] 2020-01-20 13:31
overall behaviour related to aliases is starting to be cumbersome as discussed in #223 as well, we will bring this topic on the next meeting and try to reach core devs again, because right now when querying the API when aliases are involved, partial results are returned, and users may be blind to some data

**Comment by decentraliser** [comment] 2020-01-20 15:51
For reference, there was already a first issue about that opened by a
wallet user
https://github.com/nemfoundation/nem2-desktop-wallet/issues/861

Le lun. 20 janv. 2020 à 21:31, Roger Hernandez <notifications@github.com> a
écrit :

**Comment by Vektrat** [comment] 2020-01-20 16:10
note that this issue is not `pending` server side, as far as i know it has not been decided that this would be implemented, up until now consensus has been that even though it makes sense, technically namespace resolution is not taking place server side **intentionally**

**Comment by decentraliser** [comment] 2020-01-21 02:30
sorry @Vektrat I didn't know the state of the discussions around that matter...

The thing is that currently, it is not even possible to get transactions by aliases (eg by calling `/namespace/${namespaceId}/transactions`), which we could manage client-side.

I don't think it makes sense to be able to send tx to a namespace while having no way to retrieve them from the namespace

**Comment by Vektrat** [comment] 2020-01-21 07:14
i believe you can by using the namespaceid in base32 and padding with 0s in the current endpoint, but i agree this is not very usable, though this is the kind of troubles that happen when reusing a field for different kinds of data

it does not make sense, but it's the current state of things, we will need to discuss - aliases are not the most comfortable thing to deal with

**Comment by decentraliser** [comment] 2020-01-21 07:47
> i believe you can by using the namespaceid in base32 and padding with 0s in the current endpoint

That could temporarily do the job!!! I tried different combinations but I didn't manage to make it work... could you please give me an (additional :p ) hint?

**Comment by Vektrat** [comment] 2020-01-21 07:56
> > i believe you can by using the namespaceid in base32 and padding with 0s in the current endpoint
> 
> That could temporarily do the job!!! I tried different combinations but I didn't manage to make it work... could you please give me an (additional :p ) hint?

http://api-20.us-west-1.nemtech.network:3000/account/TGCXONQXR4VCN3YAAAAAAAAAAAAAAAAAAAAAAAAA/transactions

**Comment by rg911** [comment] 2020-01-23 11:56
Don't think it is in general working, see below example

http://api-20.us-west-1.nemtech.network:3000/account/TCVMDAZSA5UKMX34YUNBQQX7FWOC7PIVU7T2WFYF/transactions

http://api-20.us-west-1.nemtech.network:3000/account/TFHKHPB7NAQIVFQAAAAAAAAAAAAAAAAAAAAAAAAA/transactions

**Comment by Vektrat** [comment] 2020-02-17 11:36
kind of duplicate of #223

**Comment by Vektrat** [comment] 2020-07-15 23:22
discussion around this has arisen again, even though resolution will still _not_ take place REST side, we are considering an alternative approach, will reference here if it progresses

**Comment by Vektrat** [comment] 2020-07-29 06:03
closing this issue in favour of https://github.com/nemtech/catapult-rest/issues/442 which should address this (for more on this decision/discussion, check https://github.com/nemtech/catapult-rest/issues/436)

**Closed by Vektrat** 2020-07-29 06:03 UTC
Labels: blocked, duplicate, enhancement
