### ISSUE TITLE
Aggregate Error in Master

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#217] opened 2019-12-02 15:39 UTC
Hi guys, I'm testing the latest master and now my aggregate e2e testing transaction started to fail.

The transaction (Account Namespace Registration):

````
{ 
   "transaction":{ 
      "deadline":"115839181160",
      "maxFee":"1000000",
      "network":144,
      "transactions":[ 
         { 
            "transaction":{ 
               "duration":"100",
               "id":"9d43c22c5ee05091",
               "name":"testaccount",
               "network":144,
               "registrationType":0,
               "signerPublicKey":"E7CAD47FA9546505D908FC841A21715CD046BCEE0B24EE986B507BDAA6043F88",
               "type":16718,
               "version":1
            }
         }
      ],
      "transactionsHash":"759547445D4617B3689A6DB9691CF5071CD11341AF3442979930C40D9D9A3BBE",
      "type":16705,
      "version":1
   }
}
````

The error that catapult-rest shows in the logs (this is not a listener status error, the transaction will just timeout). Is the transaction correct? (it used to be, this is a brand new bootstrap). If it's not, a better error handling should be implemented, the error should be a web socket status error

````
error: zmq confirmedAdded/SCUPYYARJ4YJDOAGH4SYL6B5LFYZMCAV7WMZNP45: error from zsocketaggregate cannot have partial cosignatures {"stack":"Error: aggregate cannot have partial cosignatures
    at Object.deserialize (/home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/plugins/aggregate.js:157:12) 
    at codecs.forEach.codec (/home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/modelBinary/ModelCodecBuilder.js:121:34)
    at Array.forEach (<anonymous>)
    at Object.deserialize (/home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/modelBinary/ModelCodecBuilder.js:120:12)
    at exports.Socket.<anonymous> (/home/fernando/develop/workspace-nem/catapult-rest/rest/_build/connection/MessageChannelBuilder.js:55:29)
    at exports.Socket.emit (events.js:198:13)
    at exports.Socket.EventEmitter.emit (domain.js:448:20)
    at exports.Socket.Socket._emitMessage (/home/fernando/develop/workspace-nem/catapult-rest/rest/node_modules/zeromq/lib/index.js:649:15)
    at exports.Socket.Socket._flushRead (/home/fernando/develop/workspace-nem/catapult-rest/rest/node_modules/zeromq/lib/index.js:660:10)
    at exports.Socket.Socket._flushReads (/home/fernando/develop/workspace-nem/catapult-rest/rest/node_modules/zeromq/lib/index.js:696:15)","timestamp":"2019-12-02T15:30:31.956Z"}


````

**Comment by Vektrat** [comment] 2019-12-02 15:48
possibly duplicate of #216

**Comment by Vektrat** [comment] 2019-12-02 15:49
this is weird because we have not made any changes regarding this lately, do you remember which version were you using before?

steven seems to have the same issue, can you also report what does `/diagnostic/server` say? thanks

**Comment by fboucquez** [comment] 2019-12-02 16:51
I was using the `task/add-padding-after-inner-aggregate-transactions` branch that was merged to master. After switching to master, this error started to occur.

**Closed** 2019-12-02 22:10 UTC
Labels: duplicate
